### ISSUE TITLE
update the library to the latest HF Transformers version

### ISSUE THREAD

**Issue by bhavitvyamalik** [adapter-hub/adapters#558]
How can we update the library to the latest HF Transformers version?

**Comment by lenglaender** [comment]
To update the library to the last HF transformers version, you need to merge the newest release branch of HF into it.
To do this:
1. Add HF transformers as a remote repository via `git remote add huggingface https://github.com/huggingface/transformers.git`)
2. Fetch it: `git fetch huggingface`
3. Checkout new sync branch: `git checkout -b sync/v4.30.1`
4. Merge Hugging Face code into it: `git merge v4.30.1`
5. Execute `./scripts/upstream-sync.sh v4.30.1` to resolve some merge conflicts
6. Resolve remaining merge conflicts (this part could take a while)



Currently, adapter-transformers is based on HF transformers v4.26.1 which has some known bugs. Maybe for your problems it would be enough to fix them instead of updating the HF version. To do this, copy this file in your local repository, e.g. as `diff.patch`:
```
diff --git a/src/transformers/modeling_utils.py b/src/transformers/modeling_utils.py
index 401730584..684cc00e3 100644
--- a/src/transformers/modeling_utils.py
+++ b/src/transformers/modeling_utils.py
@@ -2518,7 +2518,7 @@ class PreTrainedModel(nn.Module, ModuleUtilsMixin, GenerationMixin, PushToHubMix
                     _from_pipeline=from_pipeline,
                     **kwargs,
                 )
-            except OSError:
+            except (OSError, TypeError):
                 logger.info(
                     "Generation config file not found, using a generation config created from the model config."
                 )
@@ -2715,7 +2715,10 @@ class PreTrainedModel(nn.Module, ModuleUtilsMixin, GenerationMixin, PushToHubMix
                         del state_dict[checkpoint_key]
             return mismatched_keys
 
-        folder = os.path.sep.join(resolved_archive_file[0].split(os.path.sep)[:-1])
+        if resolved_archive_file is not None:
+            folder = os.path.sep.join(resolved_archive_file[0].split(os.path.sep)[:-1])
+        else:
+            folder = None
         if device_map is not None and is_safetensors:
             param_device_map = expand_device_map(device_map, original_loaded_keys)
```             

and apply these changes via `git apply diff.patch`

FYI: We are currently working on disentangling adapter-transformers from Hugging Face transformers which will make updating the version much easier.

**Comment by calpt** [comment]
Note that updating as above is not required anymore with the new _Adapters_ codebase. See #584.
