### ISSUE TITLE
run_fusion_glue

### ISSUE THREAD

**Issue by Lawrence0319** [adapter-hub/adapters#567]
## Environment info

    
I can't run `transformers-cli env` in Google Colab
- `adapter-transformers` version: 3.2.1
- Platform: Google Colab
- Python version: 3.10.12
- PyTorch version (GPU?): 2.0.1+cu118
- Tensorflow version (GPU?): 2.12.0
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?:

## Information

Model I am using (Bert, XLNet ...):
Adapter fusion from this website: https://github.com/adapter-hub/adapter-transformers/blob/master/examples/pytorch/adapterfusion/run_fusion_glue.py

My command in Colab:
!python drive/MyDrive/run_fusion_glue.py --model_name_or_path "bert-base-uncased" --task_name "sst-2" --data_dir "drive/MyDrive/gluedata" --output_dir "drive/MyDrive/glue"

It is stuck at the line:
from transformers import (
    AdapterArguments,
    AdapterTrainer,
    AutoConfig,
    AutoModelForSequenceClassification,
    AutoTokenizer,
    EvalPrediction,
    GlueDataset,
)

Adapter setup I am using (if any):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

**Comment by lenglaender** [comment]
Hey @Lawrence0319,
If the import does not work, it is likely that you still have the `transformers` package installed. Since `adapter-transformers` is currently a drop-in replacement for this package, it uses the same namespace (see https://docs.adapterhub.ml/installation.html).

Therefore, please uninstall `transformers` (and install `adapter-transformers` if you haven't already). After that, everything should work.
