### ISSUE TITLE
Using EncoderDecoderModel with Adapters / No module named 'adapters.models.encoder_decoder'

### ISSUE THREAD

**Issue by leaBroe** [adapter-hub/adapters#707]
## Environment info

     
- adapters version: 0.2.1
- `transformers` version: 4.39.3
- Platform: Linux-6.1.85+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.23.2
- Safetensors version: 0.4.3
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.3.0+cu121 (True)
- Tensorflow version (GPU?): 2.15.0 (True)
- Flax version (CPU?/GPU?/TPU?): 0.8.4 (gpu)
- Jax version: 0.4.26
- JaxLib version: 0.4.26
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

## Information

I am trying to use adapters with an Encoder-Decoder model. The suggested approach to do this according to the [docs](https://docs.adapterhub.ml/classes/models/encoderdecoder.html) would be:

```
from transformers import EncoderDecoderModel
import adapters 

model = EncoderDecoderModel.from_encoder_decoder_pretrained("bert-base-uncased", "bert-base-uncased")

adapters.init(model)
```

However, if I run this snipped I get the error:  

ModuleNotFoundError: No module named 'adapters.models.encoder_decoder'  

Am I missing something? Or are encoder decoder models no longer supported with my adapters version?  

Also, I am wondering whether it is also possible to load the 2 bert models first, add adapters on them and then put them inside the encoder decoder model, which would look something like:

```
encoder=BertAdapterModel.from_pretrained(....)
adapters.init(encoder)

from adapters import BnConfig

config = BnConfig(mh_adapter=True, output_adapter=True, reduction_factor=16, non_linearity="relu")

encoder.add_adapter("encoder_adapter", config=config)

#the same for decoder

 model = EncoderDecoderModel(encoder=encoder, decoder=decoder
    ...: )
```

Any help would be greatly appreciated!

**Comment by apwic** [comment]
Same issue here.

adapters version: 0.2.0

**Comment by calpt** [comment]
Hey @leaBroe and @apwic,

Thanks for reporting this and sorry for the delay in responding! This is indeed a regression in our codebase that was not intended, the code should work as shown in the snippet. We'll fix this as soon as possible!

Regarding the second question: Yes, it's totally possible to load and init the individual adapter models first and then put them into EncoderDecoderModel. The only thing different here is the missing convenience since all methods for adding, loading, saving, activating... adapters have to be called for both the encoder and decoder model separately. Until the issue with EncoderDecoderModel is fixed, this can serve as a workaround.

ps.: it's not necessary to call `adapters.init()` on `AdapterModel` classes (e.g. `BertAdapterModel`) as these automatically come with all adapter functionality initialized

**Comment by apwic** [comment]
Thanks for the response!

I am using the `EncoderDecoderModel` since I want to use BERT-based model for summarization. Since the adapters for the `EncoderDecoderModel` is not working correctly yet. I decided to use BART with the `BartAdapterModel`, haven't tested it much, but I think it should work just fine.

**Comment by calpt** [comment]
This should now be fixed when installing from the main branch of the repo

**Comment by leaBroe** [comment]
Yes it works now! Thanks a lot!!
